### ISSUE TITLE
It rains every minute

### ISSUE THREAD

**Issue by XREALM-YT** [MultiCraft-Community/weather_lite#1]
When it starts to rain i /weather none and a bit later it rains again and makes me lag it mostly lags on ios ipad

**Comment by MoNTE48** [comment]
We will reduce the amount of rain particles. The rain might start every 30-60 minutes and lasts 1-5 minutes. It can't be every minute.

**Comment by XREALM-YT** [comment]
> We will reduce the amount of rain particles. The rain might start every 30-60 minutes and lasts 1-5 minutes. It can't be every minute.

Rain goes through my glass only glass i dont see it happen with other blocks
